### PR TITLE
Script to run tracking on single video

### PR DESCRIPTION
**Pull request by yannadani**
Hi Rohit,

I have added a script that can run tracking on a single standalone video #6. 

1. No changes are made to the existing code base. All those functions which were directly using dataset roidb's are copied and rewritten accordingly to the needs inside the script.

2. The detection happens serially frame by frame. I am yet to parallelize it. But since many people asked and emailed for this script, I am sending a PR of what I have. If you have any pointers to do that or if someone could do it, it would be good.

### CODE REVIEW

**Comment by StalonWilson** [comment]
@yannadani I was looking forward to this. Thank you.
I encountered an error: 
> Offending key: AffineChannelNd.

After recompiling caffe2 and remake ops, this error still exists.
Do you have any idea to solve this?

I'm also wondering if this code can test a video without annotations?

Thank you!

**Comment by yannadani** [comment]
Hi @StalonWilson , are you able to run `launch.py` or other test scripts properly? If so, let me know the entire stack trace. Also you could try commenting out lines 323 - 325 and let me know what happens?

**Comment by StalonWilson** [comment]
Hi @yannadani  Thank you for helping me.

I'm able to run launch.py after commenting out line 50 and line 51:
```
if args.mode in ['train', 'test']: 
    other_opts += '--multi-gpu-testing '
```

I just tried commenting out lines 323-325 and got this error message:
> Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

And the complete error messages is as below:

> Traceback (most recent call last):
>   File "test_on_single_video.py", line 340, in <module>
>     main(name_scope, gpu_dev, num_images, args)
>   File "test_on_single_video.py", line 253, in main
>     model = initialize_model_from_cfg()
>   File "/home/X/Documents/DetectAndTrack/lib/core/test_engine.py", line 59, in initialize_model_from_cfg
>     init_params=cfg.TEST.INIT_RANDOM_VARS_BEFORE_LOADING)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 61, in create
>     return get_func(model_name)(init_model(model_name, train, init_params))
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 154, in keypoint_rcnn
>     add_roi_keypoint_head_func=get_func(cfg.KRCNN.ROI_KEYPOINTS_HEAD))
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 305, in build_generic_fast_rcnn_model
>     build_data_parallel_model(model, _single_gpu_build_func)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 951, in build_data_parallel_model
>     single_gpu_build_func(model)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 197, in _single_gpu_build_func
>     blob_conv, dim_conv, spatial_scale_conv = add_conv_body_func(model)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 51, in add_fpn_ResNet101_conv5_body
>     ResNet.stage_info_ResNet101_conv5)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 98, in add_fpn_generic_onto_body
>     conv_body_func(model)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/ResNet3D.py", line 389, in add_ResNet101_conv5_body
>     return add_ResNet_convX_body(model, (3, 4, 23, 3), freeze_at=2)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/ResNet3D.py", line 262, in add_ResNet_convX_body
>     p = model.AffineChannelNd(p, 'res_conv1_bn', dim_out=feat_dims[0], inplace=True)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/detector.py", line 107, in AffineChannelNd
>     return self.net.AffineChannelNd([blob_in, scale, bias], blob_in)
>   File "/home/X/caffe2/build/caffe2/python/core.py", line 2082, in __getattr__
>     ",".join(workspace.C.nearby_opnames(op_type)) + ']'
> AttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

**Comment by yannadani** [comment]
I guess you do not have nccl. I'm not really sure at this point as I have not encountered any issue like this. Let @rohitgirdhar verify this and he might be able to suggest you something!

**Comment by StalonWilson** [comment]
@yannadani You are right. Also I do not have CUB and Gloo either.

> -- Could NOT find NCCL (missing:  NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
> -- Could NOT find CUB (missing:  CUB_INCLUDE_DIR) 
> -- Could NOT find Gloo (missing:  Gloo_INCLUDE_DIR Gloo_LIBRARY) 

I'm going to install NCCL first and try to run again.

**Comment by StalonWilson** [comment]
@yannadani @rohitgirdhar 
I tried reinstalling caffe2 with binding NCCL and remade the ops inside DetectAndTrack repository.
With the ops compilation is ok:

`python tests/test_zero_even_op.py `

> ----------------------------------------------------------------------
> Ran 12 tests in 0.292s
> 
> OK
> 

The error still exists.

> AttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

My caffe2 environment:

> -- Does not need to define long separately.
> -- std::exception_ptr is supported.
> -- NUMA is available
> -- Current compiler supports avx2 extention. Will build perfkernels.
> -- Building using own protobuf under third_party per request.
> -- Use custom protobuf build.
> -- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/X/caffe2/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
> -- The BLAS backend of choice:Eigen
> -- Brace yourself, we are building NNPACK
> -- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
> -- Caffe2: Cannot find gflags automatically. Using legacy find.
> -- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
> -- Caffe2: Cannot find glog automatically. Using legacy find.
> -- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
> -- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
> -- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
> -- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
> -- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
> -- Found CUDA: /usr/local/cuda-8.0 (found suitable exact version "8.0") 
> -- OpenCV found (/usr/local/share/OpenCV)
> -- Found FFMPEG or Libav: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so, /usr/include/x86_64-linux-gnu
> Found FFMPEG/LibAV libraries
> -- Found system Eigen at /usr/local/include/eigen3
> -- Found PythonInterp: /usr/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
> -- NumPy ver. 1.14.3 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
> -- Could NOT find pybind11 (missing:  pybind11_INCLUDE_DIR) 
> -- MPI support found
> -- MPI compile flags: 
> -- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
> -- MPI LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
> -- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
> CMake Warning at cmake/Dependencies.cmake:396 (message):
>   OpenMPI found, but it is not built with CUDA support.
> Call Stack (most recent call first):
>   CMakeLists.txt:181 (include)
> 
> 
> -- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.0") 
> -- Caffe2: CUDA detected: 8.0
> -- Caffe2: CUDA nvcc is: /usr/local/cuda-8.0/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda-8.0
> -- Caffe2: Header version is: 8.0
> -- Found cuDNN: v6.0.21  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
> -- Autodetected CUDA architecture(s): 6.1 6.1 
> -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> -- Determining NCCL version from the header file: /usr/local/include/nccl.h
> -- Found NCCL (include: /usr/local/include, library: /usr/local/lib/libnccl.so)
> -- Could NOT find CUB (missing:  CUB_INCLUDE_DIR) 
> -- Could NOT find Gloo (missing:  Gloo_INCLUDE_DIR Gloo_LIBRARY) 
> -- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
> -- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
> -- CUDA detected: 8.0
> -- Found libcuda: /usr/local/cuda-8.0/lib64/stubs/libcuda.so
> -- Found libnvrtc: /usr/local/cuda-8.0/lib64/libnvrtc.so
> -- Determining NCCL version from the header file: /usr/local/include/nccl.h
> -- Found NCCL (include: /usr/local/include, library: /usr/local/lib/libnccl.so)
> -- GCC 5.4.0: Adding gcc and gcc_s libs to link line
> -- Include NCCL operators
> -- Excluding ideep operators as we are not using ideep
> -- Including image processing operators
> -- Including video processing operators
> -- Excluding mkl operators as we are not using mkl
> -- Include Observer library
> -- Using lib/python2.7/dist-packages as python relative installation path
> -- Automatically generating missing __init__.py files.
> -- A previous caffe2 cmake run already created the __init__.py files.
> CMake Warning at CMakeLists.txt:341 (message):
>   Generated cmake files are only fully tested if one builds with system glog,
>   gflags, and protobuf.  Other settings may generate files that are not well
>   tested.
> 
> 
> -- 
> -- ******** Summary ********
> -- General:
> --   CMake version         : 3.5.1
> --   CMake command         : /usr/bin/cmake
> --   Git version           : v0.1.11-9223-gf48e156-dirty
> --   System                : Linux
> --   C++ compiler          : /usr/bin/c++
> --   C++ compiler version  : 5.4.0
> --   BLAS                  : Eigen
> --   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-error=deprecated-declarations
> --   Build type            : Release
> --   Compile definitions   : 
> --   CMAKE_PREFIX_PATH     : 
> --   CMAKE_INSTALL_PREFIX  : /usr/local
> -- 
> --   BUILD_CAFFE2          : ON
> --   BUILD_ATEN            : OFF
> --   BUILD_BINARY          : ON
> --   BUILD_CUSTOM_PROTOBUF : ON
> --     Link local protobuf : ON
> --   BUILD_DOCS            : OFF
> --   BUILD_PYTHON          : ON
> --     Python version      : 2.7.12
> --     Python includes     : /usr/include/python2.7
> --   BUILD_SHARED_LIBS     : ON
> --   BUILD_TEST            : OFF
> --   USE_ASAN              : OFF
> --   USE_ATEN              : OFF
> --   USE_CUDA              : ON
> --     CUDA static link    : OFF
> --     USE_CUDNN           : ON
> --     CUDA version        : 8.0
> --     cuDNN version       : 6.0.21
> --     CUDA root directory : /usr/local/cuda-8.0
> --     CUDA library        : /usr/local/cuda-8.0/lib64/stubs/libcuda.so
> --     cudart library      : /usr/local/cuda-8.0/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
> --     cublas library      : /usr/local/cuda-8.0/lib64/libcublas.so;/usr/local/cuda-8.0/lib64/libcublas_device.a
> --     cufft library       : /usr/local/cuda-8.0/lib64/libcufft.so
> --     curand library      : /usr/local/cuda-8.0/lib64/libcurand.so
> --     cuDNN library       : /usr/local/cuda-8.0/lib64/libcudnn.so
> --     nvrtc               : /usr/local/cuda-8.0/lib64/libnvrtc.so
> --     CUDA include path   : /usr/local/cuda-8.0/include
> --     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
> --     CUDA host compiler  : /usr/bin/cc
> --     USE_TENSORRT        : OFF
> --   USE_ROCM              : OFF
> --   USE_EIGEN_FOR_BLAS    : ON
> --   USE_FFMPEG            : ON
> --   USE_GFLAGS            : ON
> --   USE_GLOG              : ON
> --   USE_GLOO              : ON
> --     USE_GLOO_IBVERBS    : OFF
> --   USE_LEVELDB           : ON
> --     LevelDB version     : 1.18
> --     Snappy version      : 1.1.3
> --   USE_LITE_PROTO        : OFF
> --   USE_LMDB              : ON
> --     LMDB version        : 0.9.17
> --   USE_METAL             : OFF
> --   USE_MKL               : 
> --   USE_MOBILE_OPENGL     : OFF
> --   USE_MPI               : ON
> --   USE_NCCL              : ON
> --     USE_SYSTEM_NCCL     : OFF
> --   USE_NERVANA_GPU       : OFF
> --   USE_NNPACK            : ON
> --   USE_OBSERVERS         : ON
> --   USE_OPENCL            : OFF
> --   USE_OPENCV            : ON
> --     OpenCV version      : 3.2.0
> --   USE_OPENMP            : OFF
> --   USE_PROF              : OFF
> --   USE_REDIS             : OFF
> --   USE_ROCKSDB           : OFF
> --   USE_ZMQ               : OFF
> --   Public Dependencies  : Threads::Threads;gflags;glog::glog
> --   Private Dependencies : nnpack;cpuinfo;/usr/lib/x86_64-linux-gnu/liblmdb.so;/usr/lib/x86_64-linux-gnu/libleveldb.so;/usr/lib/x86_64-linux-gnu/libsnappy.so;/usr/lib/x86_64-linux-gnu/libnuma.so;opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_video;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;onnxifi_loader;gcc_s;gcc;dl
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/X/caffe2/build

Any suggestion is appreciated!
Or how could I do to close multi-gpu?

**Comment by StalonWilson** [comment]
OK.
After I installed and bind pybind11 and NCCL, I also commented out line 324, I encountered this error message:

> Traceback (most recent call last):
>   File "test_on_single_video.py", line 341, in <module>
>     main(name_scope, gpu_dev, num_images, args)
>   File "test_on_single_video.py", line 253, in main
>     model = initialize_model_from_cfg()
>   File "/home/X/Documents/DetectAndTrack/lib/core/test_engine.py", line 59, in initialize_model_from_cfg
>     init_params=cfg.TEST.INIT_RANDOM_VARS_BEFORE_LOADING)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 61, in create
>     return get_func(model_name)(init_model(model_name, train, init_params))
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 154, in keypoint_rcnn
>     add_roi_keypoint_head_func=get_func(cfg.KRCNN.ROI_KEYPOINTS_HEAD))
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 305, in build_generic_fast_rcnn_model
>     build_data_parallel_model(model, _single_gpu_build_func)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 951, in build_data_parallel_model
>     single_gpu_build_func(model)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/model_builder.py", line 197, in _single_gpu_build_func
>     blob_conv, dim_conv, spatial_scale_conv = add_conv_body_func(model)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 51, in add_fpn_ResNet101_conv5_body
>     ResNet.stage_info_ResNet101_conv5)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 99, in add_fpn_generic_onto_body
>     blobs_fpn, dim_fpn, spatial_scales_fpn = add_fpn(model, stage_info_func())
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 135, in add_fpn
>     model, fpn_top, fpn_lateral, fpn_bottom, dim_top, dim_lateral)
>   File "/home/X/Documents/DetectAndTrack/lib/modeling/FPN3D.py", line 211, in add_topdown_lateral_module
>     temp = model.net.UpsampleNearest(
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py", line 2082, in __getattr__
>     ",".join(workspace.C.nearby_opnames(op_type)) + ']'
> AttributeError: Method UpsampleNearest is not a registered operator. Did you mean: []

I used the command:

`python test_on_single_video.py          --cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml          --video test.AVI          --output output/tracks_and_visualizations          TEST.WEIGHTS pretrained_models/model_final.pkl NUM_GPUS 2`

Is this error related to the weight structure?

**Comment by rohitgirdhar** [comment]
Thanks @yannadani for the PR!

**Comment by rohitgirdhar** [comment]
@StalonWilson You might want to look at the instructions on compiling custom ops [here](https://github.com/facebookresearch/DetectAndTrack#compile-some-custom-ops). As mentioned there, you can copy over the files to the detectron module folder in the caffe2 repo, and then it should definitely work.

**Comment by StalonWilson** [comment]
@rohitgirdhar Yes. I have done this and recompile caffe2. But the error is the same.

**Comment by StalonWilson** [comment]
@rohitgirdhar @yannadani 
I reinstalled all the stuff. I also found the following message came from `c2.import_custom_ops()`

> Offending key: AffineChannelNd.

As commenting out the line 

> dyndep.InitOpsLibrary(custom_ops_lib)

I can run the following procedure. However, now it goes core-dumped after I used this command

`export CUDA_VISIBLE_DEVICES="0,1"`

`python test_on_single_video.py --cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml --video test.AVI --output output/tracks_and_visualizations TEST.WEIGHTS pretrained_models/model_final.pkl NUM_GPUS 2 USE_NCCL True` .

The error occurs as following, in the `test.py` function `workspace.RunNet(model.net.Proto().name)`.

> I0726 00:55:14.527932 26360 net_async_base.cc:435] Using specified CPU pool size: 8; NUMA node id: -1
> I0726 00:55:14.527945 26360 net_async_base.cc:440] Created new CPU pool, size: 8; NUMA node id: -1
> *** Aborted at 1532537715 (unix time) try "date -d @1532537715" if you are using GNU date ***
> PC: @           0x53c390 _PyTrash_thread_destroy_chain
> *** SIGSEGV (@0xb8) received by PID 26360 (TID 0x7f22e3fff700) from PID 184; stack trace: ***
>     @     0x7f23731f8390 (unknown)
>     @           0x53c390 _PyTrash_thread_destroy_chain
>     @           0x55eba3 (unknown)
>     @           0x4c195b PyEval_EvalFrameEx
>     @           0x4b9ab6 PyEval_EvalCodeEx
>     @           0x4c1e6f PyEval_EvalFrameEx
>     @           0x4b9ab6 PyEval_EvalCodeEx
>     @           0x4d54b9 (unknown)
>     @           0x4eebee (unknown)
>     @           0x4a577e PyObject_Call
>     @           0x4c5e10 PyEval_CallObjectWithKeywords
>     @     0x7f23536ee8a0 pybind11::detail::object_api<>::operator()<>()
>     @     0x7f23536f064e caffe2::python::PythonOpBase<>::RunOnDevice()
>     @     0x7f23536ed7f3 caffe2::Operator<>::Run()
>     @     0x7f2353703b79 _ZN6caffe213GPUFallbackOpINS_6python8PythonOpINS_10CPUContextELb0EEENS_11SkipIndicesIJEEEE11RunOnDeviceEv
>     @     0x7f235370227d caffe2::Operator<>::RunAsync()
>     @     0x7f2352961868 caffe2::AsyncNetBase::run()
>     @     0x7f23529a87d7 _ZZN6caffe218AsyncSchedulingNet8scheduleEibENKUlvE_clEv
>     @     0x7f2352966a04 caffe2::TaskThreadPool::main_loop()
>     @     0x7f23567eac80 (unknown)
>     @     0x7f23731ee6ba start_thread
>     @     0x7f2372f2441d clone
>     @                0x0 (unknown)
> Segmentation fault (core dumped)

And my GPU environment is shown as following

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   53C    P8    15W / 180W |     10MiB /  8112MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   42C    P8    14W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

Could you please give me some suggestions about this? Thank you.

**Comment by StalonWilson** [comment]
Now I figured out the problems.
Thank you, @yannadani and @rohitgirdhar .

**Comment by rohitgirdhar** [comment]
Good to know, @StalonWilson. Also might be useful for future users if you can share what you found was the problem.

**Comment by StalonWilson** [comment]
Sure.
First, make sure to install `pybind11`, `nccl` and `pandas`.
I installed pybind11 and pandas by using

`pip install pybind11` and `pip install pandas==0.22.0`.

Don't forget to record the `pybind11` include location.

`nccl` needs to be installed from [source](https://github.com/NVIDIA/nccl).
Just install it by following the official steps.

When installing [caffe2](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=prebuilt), note that using `cmake` to bind `pybind11` first, like

`cmake -Dpybind11_INCLUDE_DIR=/usr/local/include/python2.7/`

You may need to copy the file `lib/ops/affine_channel_nd_op.*` to `caffe2/modules/detectron/` if you meet some difficulties like I did.

Then, press the following command to compile, link and install caffe2

```
sudo make -j
sudo make install -j
```

After pass the test of caffe2, remember to go back to compile custom ops

```
cd ../DetectAndTrack/lib
make && make ops
```

Now you may encounter the following error message if you directly run the `launch.py` or `test_on_single_video.py`

> Offending key: AffineChannelNd.

The key in `lib/utils/c2.import_custom_ops()` and another same key in `lib/utils/c2.import_detectron_ops()` seem to contradict to one another.
So I commented out line 56 in `lib/utils/c2.import_custom_ops()` as following

```
def import_custom_ops():
    """Import custom ops."""
    custom_ops_lib = envu.get_custom_ops_lib()
    #dyndep.InitOpsLibrary(custom_ops_lib)
```

Finally, go to `lib` and compile the custom ops

```
cd ../DetectAndTrack/lib
make && make ops
```

Now everything should work.

**Comment by rohitgirdhar** [comment]
@yannadani Sorry I didn't realize when accepting the PR, but could you move the script into the `tools/` folder? (And update the readme?)

**Comment by StalonWilson** [comment]
@yannadani 
There might be a typo in [here](https://github.com/facebookresearch/DetectAndTrack/blob/2cc9b779bab1ddddd0e387859ba6ebabb950d481/test_on_single_video.py#L146)

curr_img_path --> cur_img_path

**Pull request merged**
