### PR TITLE
add codes for predicting pose with 3D pretrained model

### PR DESCRIPTION
**Pull request by Marcovaldong**
Ref #29

### CODE REVIEW

**Comment by rohitgirdhar** [comment]
Great, thanks @Marcovaldong! @heury, since you asked for this feature, would you mind testing if it works for you?

**Comment by heury** [comment]
@rohitgirdhar It is working nicely. Thanks @Marcovaldong

**Comment by rohitgirdhar** [comment]
Cool, thanks!

**Comment by kaisark** [comment]
@Marcovaldong @heury  What does the 3d output look like compared to 2D output? Are you running the 3D model against 2d Video or against depth data (RGB-D)? Can someone upload a GIF of their output? Can this output be added to the project readme? Thanks!

**Pull request merged**
